name: krili
description: "A Lodging flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.7.1
  flutter_map_location_marker: ^9.0.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  geolocator: ^12.0.0
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  modal_bottom_sheet: ^3.0.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
